
# Coordinate space 
_target_: symdrift.generative.EquivariantDriftingField
temperatures: [0.02, 0.05, 0.2]
normalize_over_x: true
normalize_drift: true
# Only rotational equivariant, but not permutation equivariant.
aligned: true
permuted: false
brute_force_permutations: false 