
# Coordinate space 
_target_: symdrift.generative.EquivariantDriftingField
temperatures: [0.02, 0.05, 0.2]
normalize_over_x: false
normalize_drift: true
# Naive drift does not respect any symmetry of the system.
aligned: false
permuted: false
brute_force_permutations: false 