[build-system]
requires = ["setuptools", "wheel", "cython==3.0.11", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "symdrift"
# Declaring that the version will be read dynamically.
# This helps us not having to specify the version twice.
# We have to specify the version only in schnetpack.__version__
# see [tool.setuptools.dynamic] below
dynamic = ["version"]
authors = [
    { name = "Samir Darouich" },
]

description = "SymDrift: A framework that makes the drifting field itself symmetry-aware"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "torch>=2.8.0,<2.9",
    "pytorch-lightning>=2.6.0",
    "torch_geometric>2.6",
    "wandb>=0.12.9",
    "ase>=3.21",
    "hydra-core>=1.1.0",
    "rich",
    "tqdm",
    "e3nn",
    "pymatgen",
    "py3Dmol",
    "einops",
    "rdkit",
    "scikit-learn",
    "datamol",
    "cython==3.0.11",
    "pynauty",
]

[tool.setuptools]
package-dir = { "" = "src" }
script-files = [
    "src/scripts/symdrift_train",
    "src/scripts/symdrift_sample",
    "src/scripts/symdrift_covmat_evaluation",
]

[tool.setuptools.dynamic]
version = {attr = "symdrift.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

#[tool.setuptools.package-data]
#symdrift = ["configs/**/*.yaml"]