defaults:
  - /dataset: transition1x
  - _self_

seed: 42

run:
  experiment: ts_physics
  id: ${uuid:1}
  path: ${run.work_dir}/samples
  work_dir: ${hydra:runtime.cwd}

diffusion:
  _target_: tspath.trainer.ReactionPath

  n_sample_steps: 10
  save_trajectory: false
  
  model:
    _target_: tspath.model.EquiformerV2
    max_radius: 11.0
    num_layers: 6
    num_distance_basis: 64

  generative_scheduler:
    _target_: tspath.generative.VPGaussianDDPM
    noise_schedule:
      _target_: tspath.generative.PolynomialSchedule
      T: 1000

  checkpoint_path: ???

hydra:
    job:
      chdir: True
    # output paths for hydra logs
    run:
        dir: ${run.path}/${run.id}