defaults:
  - /dataset: transition1x
  - _self_

seed: 42

run:
  experiment: tspath
  id: ${uuid:1}
  path: ${run.work_dir}/runs
  work_dir: ${hydra:runtime.cwd}
  ckpt_path: null # if training should be continued from a checkpoint

diffusion:
  _target_: tspath.trainer.ReactionPath
  sample_every_epoch: 10000
  n_sample_steps: 10

  model:
    _target_: tspath.model.EquiformerV2
    max_radius: 11.0
    num_layers: 6
    num_distance_basis: 64
    
  generative_scheduler:
    _target_: tspath.generative.flow_scheduler.VPGaussianDDPM
    noise_schedule:
      _target_: tspath.generative.PolynomialSchedule
      T: 1000

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1e-2
  
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: ${trainer.max_epochs}

  pretrained: null # path to pretrained model checkpoint for fine-tuning


trainer:
  max_epochs: 1000
  gradient_clip_val: 100.0

callbacks:
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/loss"
    save_top_k: 1
    save_last: True
    mode: "min"
    dirpath: 'checkpoints/'
    filename: "epoch_{epoch}-step_{step}"

  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/loss"
    patience: 100
    mode: "min"
  
  ema_callback:
    _target_ : tspath.model.ema.EMA
    decay: 0.9999
    validate_original_weights: true
    every_n_steps: 100

loggers:
  wandb_logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    save_dir: "."
    name: ${run.id}
    id: ${run.id}
    project: ${run.experiment}

hydra:
    job:
      chdir: True
    # output paths for hydra logs
    run:
        dir: ${run.path}/${run.id}