# Dataset configuration for GEOM QM9 dataset

# Dataset specific parameters (assume data lies in the run folder under the dataset name e.g. data/geom_qm9 for the geom_qm9 dataset)
name: geom_qm9
root: ${run.work_dir}/data/${dataset.name}
identifier: smiles
split_identifier: geomol_cleaned

# Batch size defines the number of graphs from the dataset (can be seen as postive class)
# where each graph has n_conformers, which can be seen as positive samples.
batch_size: 2

# In the case of testing, we loop with 'test_batch_size' through the test set
# and generate 'x' samples per graph, where we subdivide the 'x' samples using
# 'batch_size' to avoid memory issues. 
test_batch_size: 1

# Dataloader parameters
num_workers: 4
persistent_workers: true
pin_memory: true
follow_batch: [x_conf] # creates additional batch mask for each conformer

# Define transforms to apply when loading data
subselect_top_k_conformers:
  _target_: symdrift.datasets.BoltzmannWeightingConformers
  keep_top_n: 30

augment_conformers:
  _target_: symdrift.datasets.ConformerAugment
  num_augs: 10
  rotate: true
  permute: true

train_transform:
  _target_: torch_geometric.transforms.Compose
  transforms:
    - ${dataset.subselect_top_k_conformers}
    - ${dataset.augment_conformers}

val_transform:
  _target_: torch_geometric.transforms.Compose
  transforms:
    - ${dataset.subselect_top_k_conformers}
    - ${dataset.augment_conformers}

# Define datamodule for training
datamodule:
  _target_: symdrift.datasets.DataModule
  dataset:
    _target_: symdrift.datasets.ConformerDatasetInMemory
    root: ${dataset.root}
    source: ${dataset.name}
    identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.val_transform}
  train_batch_size: ${dataset.batch_size}
  val_batch_size: ${dataset.batch_size}
  test_batch_size: ${dataset.test_batch_size}
  num_workers: ${dataset.num_workers}
  pin_memory: ${dataset.pin_memory}
  persistent_workers: ${dataset.persistent_workers}
  follow_batch: ${dataset.follow_batch}
  shuffle_train: true
  drop_last_train: false

# Define seperate test loader
test_dataloader:
  _target_: torch_geometric.loader.DataLoader
  dataset: 
    _target_: symdrift.datasets.ConformerDatasetTest
    root: ${dataset.root}
    source: ${dataset.name}
    identifier: ${dataset.identifier}
  batch_size: ${dataset.test_batch_size}
  num_workers: ${dataset.num_workers}
  pin_memory: ${dataset.pin_memory}
  persistent_workers: ${dataset.persistent_workers}
  follow_batch: ${dataset.follow_batch}
  shuffle: false
  drop_last: false