defaults:
  - /optimizer@optimizer: adamw
  - /scheduler@scheduler: null
  - _self_

model:
  _target_: symdrift.model.GotenNet
  sphere_channels: 256
  node_attr_dim: 10
  num_layers: 3
  num_distance_basis: 20
  max_radius: 11.0
  radial_basis: 'expnorm'
  activation: "swish"
  max_z: 100
  weight_init: "xavier_uniform"
  bias_init: "zeros"
  int_layer_norm: ""
  int_vector_norm: ""
  num_heads: 8
  attn_dropout: 0.1
  edge_updates: 'norej'
  aggr: "add"
  edge_ln: ''
  sep_int_vec: True
  lmax: 2

  # no time embedding since we are doing one shot prediction
  use_time_emb: false

optimizer:
  lr: 0.0005

grad_norm_max_val: 5.0