lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
  
best_model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: 'checkpoints/'
  filename: "epoch_{epoch}-step_{step}"
  monitor: val/loss
  mode: min
  every_n_epochs: 1
  save_top_k: 3

last_model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "checkpoints/"
  filename: "last"
  every_n_epochs: 1