
# Coordinate space 
_target_: tspath.generative.EquivariantDriftingField
temperatures: [0.02, 0.05, 0.2]
normalize_over_x: false
normalize_drift: true
aligned: true
permuted: true
# only feasible for small molecues. Otherwise iterative algorithm (high chance to get stuck in local minima)
brute_force_permutations: true 