
# Drifting in embedding space, which does guarantee invariance
# to the symmetries of the system.
_target_: tspath.generative.DriftingField
temperatures: [0.02, 0.05, 0.2]
normalize_over_x: false
normalize_drift: true