
model:
  _target_: tspath.model.TorchMDDynamics
  sphere_channels: 160
  max_radius: 11.0
  num_layers: 20
  num_distance_basis: 64
  rbf_type: expnorm
  trainable_rbf: true
  activation: silu
  neighbor_embedding: true
  max_z: 100
  node_attr_dim: 10
  edge_attr_dim: 1
  attn_activation: silu
  num_heads: 8
  distance_influence: both
  reduce_op: sum
  qk_norm: true
  clip_during_norm: true
  so3_equivariant: false
  output_layer_norm: true
  # used to switch parity of predictions (to correct chirality)
  parity_switch: null # post_hoc 
  # dont use embedding for time conditioning
  use_noise_schedule_sigma_encoding: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 7.0e-4
  weight_decay: 1e-8

scheduler:
  _target_: tspath.model.CosineAnnealingWarmupRestarts
  _partial_: true
  first_cycle_steps: 250_000
  cycle_mult: 1.0
  max_lr: 7e-4
  min_lr: 1e-8
  warmup_steps: 0
  gamma: 0.05
  last_epoch: -1
  interval: step

gradient_clip_val: 1.0