
_target_: tspath.model.GaussianMomentEmbedder

# if atom emebedding is used, then the gaussian radial basis are reduced to this number of basis
n_radial: 4

# number of gaussians for radial basis
n_basis: 4

# First 4 contractions are distance based, the last 4 are angle based
n_contr: 4

# maximum distance for the radial basis functions
max_radius: 15.0

# if pair wise embeddings should be learned to scale the radial functions
use_atom_type_embeddings: false