# Dataset configuration for GEOM QM9 dataset

# Dataset specific parameters (assume data lies in the run folder under the dataset name, e.g. data/geom_qm9 for the geom_qm9 dataset)
name: geom_qm9
root: ${run.work_dir}/data/${dataset.name}
identifier: smiles
split_identifier: geomol
batch_size: 2
num_workers: 0
persistent_workers: false
pin_memory: false
follow_batch: [x_conf] # creates additional batch mask for each conformer

# Define training and validation datasets and dataloaders
train_dataset:
  _target_: tspath.datasets.ConformerDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: train
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}
  sort_by_boltzmann_weight: true
  keep_top_n: 30

val_dataset:
  _target_: tspath.datasets.ConformerDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: val
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}
  sort_by_boltzmann_weight: true
  keep_top_n: 30

test_dataset:
  _target_: tspath.datasets.ConformerDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: test
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}

train_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: True

val_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: False

test_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: False
