# Dataset configuration for GEOM DRUG dataset

# Dataset specific parameters (assume data lies in the run folder under the dataset name e.g. data/geom_qm9 for the geom_qm9 dataset)
name: geom_drugs
root: ${run.work_dir}/data/${dataset.name}
identifier: smiles
split_identifier: geomol_cleaned

# Batch size defines the number of graphs from the dataset (can be seen as postive class)
# where each graph has n_conformers, which can be seen as positive samples.
batch_size: 2

# In the case of testing, we loop with 'test_batch_size' through the test set
# and generate 'x' samples per graph, where we subdivide the 'x' samples using
# 'batch_size' to avoid memory issues. 
test_batch_size: 1

# Dataloader parameters
num_workers: 0
persistent_workers: false
pin_memory: false
follow_batch: [x_conf] # creates additional batch mask for each conformer

# Define transforms to apply when loading data
train_transform:
  _target_: torch_geometric.transforms.Compose
  transforms:
    - _target_: tspath.datasets.BoltzmannWeightingConformers
      keep_top_n: 30

val_transform:
  _target_: torch_geometric.transforms.Compose
  transforms:
    - _target_: tspath.datasets.BoltzmannWeightingConformers
      keep_top_n: 30

test_transform: null

# Define datamodule
datamodule:
  _target_: tspath.datasets.DataModule
  dataset:
    _target_: tspath.datasets.ConformerDatasetDisk
    root: ${dataset.root}
    source: ${dataset.name}
    identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.val_transform}
  test_transform: ${dataset.test_transform}
  train_batch_size: ${dataset.batch_size}
  val_batch_size: ${dataset.batch_size}
  test_batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  pin_memory: ${dataset.pin_memory}
  persistent_workers: ${dataset.persistent_workers}
  follow_batch: ${dataset.follow_batch}
  shuffle_train: true
  drop_last_train: false

# Define test loader
test_dataloader:
  _target_: torch_geometric.loader.DataLoader
  dataset: 
    _target_: tspath.datasets.ConformerDatasetTest
    root: ${dataset.root}
    source: ${dataset.name}
    identifier: ${dataset.identifier}
  batch_size: ${dataset.test_batch_size}
  num_workers: ${dataset.num_workers}
  pin_memory: ${dataset.pin_memory}
  persistent_workers: ${dataset.persistent_workers}
  follow_batch: ${dataset.follow_batch}
  shuffle: false
  drop_last: false