# Dataset configuration for RDB7 dataset

# Dataset specific parameters (assume data lies in the run folder under the dataset name e.g. data/geom_qm9 for the geom_qm9 dataset)
name: rdb7
root: ${run.work_dir}/data/${dataset.name}
identifier: rxn
split_identifier: random

batch_size: 2
num_workers: 0
persistent_workers: false
pin_memory: false
follow_batch: [x_conf] # creates additional batch mask for each conformer

# split used during sampling (can be train/val/test)
sampling_split: test

# Define transforms to apply when loading data
train_transform: null

val_transform: null

test_transform: null

# Define datamodule
datamodule:
  _target_: tspath.datasets.DataModule
  dataset:
    _target_: tspath.datasets.ReactionDataset
    root: ${dataset.root}
    source: ${dataset.name}
    identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.val_transform}
  test_transform: ${dataset.test_transform}
  train_batch_size: ${dataset.batch_size}
  val_batch_size: ${dataset.batch_size}
  test_batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  pin_memory: ${dataset.pin_memory}
  persistent_workers: ${dataset.persistent_workers}
  follow_batch: ${dataset.follow_batch}
  shuffle_train: true
  drop_last_train: false