# Dataset configuration for GEOM Drugs dataset

# Dataset specific parameters
name: rdb7
root: ${run.work_dir}/data/${dataset.name}
identifier: rxn
split_identifier: random
batch_size: 2
num_workers: 0
persistent_workers: false
pin_memory: false
follow_batch: [x_conf] # creates additional batch mask for each conformer


# Define training and validation datasets and dataloaders
train_dataset:
  _target_: tspath.datasets.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: train
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}

val_dataset:
  _target_: tspath.datasets.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: val
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}

test_dataset:
  _target_: tspath.datasets.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: test
  split_identifier: ${dataset.split_identifier}
  identifier: ${dataset.identifier}

train_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: True

val_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: False

test_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  persistent_workers: ${dataset.persistent_workers}
  pin_memory: ${dataset.pin_memory}
  follow_batch: ${dataset.follow_batch}
  shuffle: False
