
name: cc

n_samples: 1000
r0: 1.54
theta0: 120.0
bond_k: 8.0
angle_k: 1.5
T: 300.0
seed: null
batch_size: 256
augment_with_rotations: true

# Define training and validation datasets and dataloaders
train_dataset:
  _target_: tspath.datasets.toy.ToyMoleculeDataset
  name: ${dataset.name}
  n_samples: ${dataset.n_samples}
  r0: ${dataset.r0}
  theta0: ${dataset.theta0}
  bond_k: ${dataset.bond_k}
  angle_k: ${dataset.angle_k}
  T: ${dataset.T}
  augment_with_rotations: ${dataset.augment_with_rotations}
  seed: ${dataset.seed}

val_dataset:
  _target_: tspath.datasets.toy.ToyMoleculeDataset
  name: ${dataset.name}
  n_samples: ${dataset.n_samples}
  n_samples: ${dataset.n_samples}
  r0: ${dataset.r0}
  theta0: ${dataset.theta0}
  bond_k: ${dataset.bond_k}
  angle_k: ${dataset.angle_k}
  T: ${dataset.T}
  augment_with_rotations: ${dataset.augment_with_rotations}
  seed: ${dataset.seed}

test_dataset:
  _target_: tspath.datasets.toy.ToyMoleculeDataset
  name: ${dataset.name}
  n_samples: ${dataset.n_samples}
  n_samples: ${dataset.n_samples}
  r0: ${dataset.r0}
  theta0: ${dataset.theta0}
  bond_k: ${dataset.bond_k}
  angle_k: ${dataset.angle_k}
  T: ${dataset.T}
  augment_with_rotations: ${dataset.augment_with_rotations}
  seed: ${dataset.seed}

train_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  shuffle: True

val_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  shuffle: False

test_dataloader:
  _target_: torch_geometric.loader.DataLoader
  batch_size: ${dataset.batch_size}
  shuffle: False