# Dataset configuration for Transition1x reaction dataset

# Dataset specific parameters
name: transition1x
root: ???
identifier: rxn
use_torch_geometric_dataloader: true

# Define training and validation datasets and dataloaders
train_dataset:
  _target_: tspath.datasets.reaction.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: train
  identifier: ${dataset.identifier}

val_dataset:
  _target_: tspath.datasets.reaction.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: val
  identifier: ${dataset.identifier}

test_dataset:
  _target_: tspath.datasets.reaction.ReactionDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: test
  identifier: ${dataset.identifier}

train_dataloader:
  batch_size: 16
  num_workers: 4
  persistent_workers: True
  shuffle: True

val_dataloader:
  batch_size: 16
  num_workers: 4
  persistent_workers: True
  shuffle: False

test_dataloader:
  batch_size: 16
  num_workers: 4
  persistent_workers: True
  shuffle: False
