# Dataset configuration for Transition1x reaction dataset

# Dataset specific parameters
name: transition1x
root: ???
identifier: rxn
split_identifier: null # just assume split is called "split_${name}"
use_torch_geometric_dataloader: true

# Batch sampler configuration for composition-based sampling
k: 2  # Number of samples per composition
n: 64  # Number of compositions per batch
resample: true  # Whether to resample molecules for compositions if there are not enough unique molecules

# Define training and validation datasets and dataloaders
train_dataset:
  _target_: tspath.datasets.molecule.MoleculeDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: train
  identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}

val_dataset:
  _target_: tspath.datasets.molecule.MoleculeDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: val
  identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}

test_dataset:
  _target_: tspath.datasets.molecule.MoleculeDataset
  root: ${dataset.root}
  source: ${dataset.name}
  split: test
  identifier: ${dataset.identifier}
  split_identifier: ${dataset.split_identifier}

train_dataloader:
  __target__: torch_geometric.loader.DataLoader
  batch_sampler:
    _target_: tspath.datasets.CompositionBatchSampler
    k: ${dataset.k}
    n: ${dataset.n}
    resample: ${dataset.resample}
    shuffle: True
  num_workers: 4
  persistent_workers: True
  # batch_size: 32
  # shuffle: True

val_dataloader:
  __target__: torch_geometric.loader.DataLoader
  batch_sampler:
    _target_: tspath.datasets.CompositionBatchSampler
    k: ${dataset.k}
    n: ${dataset.n}
    resample: False
    shuffle: False
  num_workers: 4
  persistent_workers: True
  # batch_size: 32
  # shuffle: False

test_dataloader:
  __target__: torch_geometric.loader.DataLoader
  batch_sampler:
    _target_: tspath.datasets.CompositionBatchSampler
    k: ${dataset.k}
    n: ${dataset.n}
    resample: False
    shuffle: False
  num_workers: 4
  persistent_workers: True
  # batch_size: 32
  # shuffle: False
